#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Dec 15 21:23:15 2021

@author: dell
"""

import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import spearmanr


beha_total_score = r'/mnt/data/Project/DCM/participants.xlsx'
data = pd.read_excel(beha_total_score)
data = data.dropna(subset=['2D_acc'])


sns.set_theme(style="darkgrid")


g = sns.jointplot(x="Age", y="2D_acc", data=data,
                  kind="reg", truncate=False,
                  xlim=(8, 30), ylim=(0.4, 1),
                  color="m", height=6)
savepath = r'/home/dell/Documents/worklog/2021.12.15/age_score.png'
g.savefig(savepath,bbox_inches='tight',pad_inches=0,dpi=300)

res = spearmanr(data['Age'],data['2D_acc'])
r = round(res[0],3)
p = res[1]