#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Dec 15 21:55:45 2021

@author: dell
"""
import os
import pandas as pd 
from nilearn.masking import apply_mask
from nilearn.image import load_img,resample_to_img

df_path = r'/mnt/data/Project/DCM/participants.xlsx'
df = pd.read_excel(df_path)
participant_id = df['Participant_ID']\

analysis_dir = r'/mnt/data/Project/DCM/BIDS/derivatives/nilearn'
sub_analysis_list = os.listdir(analysis_dir)

hexagon_effect = [] 
for pid in participant_id:
    if 'sub-{}'.format(pid[4:]) in sub_analysis_list:
        print('sub-{}'.format(pid[4:]))
        zmap_path = os.path.join(analysis_dir,r'sub-{}/game1/6fold/ftest_map.nii.gz'.format(pid[4:]))
        zmap = load_img(zmap_path)
        mask = load_img(r'/mnt/data/Template/EC_anatomy_roi.nii.gz')
        mask = resample_to_img(mask, zmap,interpolation='nearest')
        zmap_masked = apply_mask(zmap,mask)
        mean_z = zmap_masked.mean()
        hexagon_effect.append(mean_z)
    else:
        hexagon_effect.append(float('nan'))
    

df['hexagon_effect'] = hexagon_effect